# ocserv 1.5.0 configuration
# Generated by the Synology ocserv package installer.
# Full reference: https://ocserv.gitlab.io/www/manual.html

# ── Network ───────────────────────────────────────────────────────────────────
tcp-port = @@VPN_PORT@@
udp-port = @@VPN_PORT@@

# ── TLS certificates ──────────────────────────────────────────────────────────
server-cert = @@SERVER_CERT@@
server-key  = @@SERVER_KEY@@
# ca-cert is required only for certificate-based client authentication.
# Uncomment and set path if you use client certificates or RADIUS with EAP-TLS.
#ca-cert =

# ── Authentication ────────────────────────────────────────────────────────────
# Exactly one auth line must be active.

# Option 1: Local password file
# Manage users: ocpasswd -c /var/packages/ocserv/var/lib/ocpasswd <username>
@@AUTH_LOCAL_COMMENT@@auth = "plain[passwd=/var/packages/ocserv/var/lib/ocpasswd]"

# Option 2: RADIUS (per-user, uses Class attribute for group assignment)
@@AUTH_RADIUS_COMMENT@@auth = "radius[config=@@RADIUS_CONFIG@@,groupconfig=true]"

# ── Logging ───────────────────────────────────────────────────────────────────
syslog    = false
log-level = 1

# ── Process / privilege ───────────────────────────────────────────────────────
run-as-user  = nobody
run-as-group = nogroup

# ── Client addressing ─────────────────────────────────────────────────────────
ipv4-network = 192.168.120.0/24
dns          = 8.8.8.8
dns          = 8.8.4.4

# ── Routing ───────────────────────────────────────────────────────────────────
route = default

# ── Session limits ────────────────────────────────────────────────────────────
max-clients      = 16
max-same-clients = 2
keepalive        = 32400
dpd              = 90
mobile-dpd       = 1800

# ── TUN device ────────────────────────────────────────────────────────────────
device = vpns

# ── Compatibility ─────────────────────────────────────────────────────────────
cisco-client-compat = true
dtls-legacy         = true
