# ocserv configuration
# Generated by the Synology ocserv package installer.
# Full reference: https://ocserv.gitlab.io/www/manual.html

# ── Network ───────────────────────────────────────────────────────────────────
tcp-port = @@VPN_PORT@@
udp-port = @@VPN_PORT@@

# ── TLS certificates ──────────────────────────────────────────────────────────
server-cert = @@SERVER_CERT@@
server-key  = @@SERVER_KEY@@
# Uncomment if using certificate-based client auth:
# ca-cert   = @@CA_CERT@@

# ── Authentication ────────────────────────────────────────────────────────────
# Manage users with:  ocpasswd -c /var/packages/ocserv/var/lib/ocpasswd <user>
auth = "plain[passwd=/var/packages/ocserv/var/lib/ocpasswd]"

# ── Logging ───────────────────────────────────────────────────────────────────
syslog     = false
log-level  = 1

# ── Process / privilege ───────────────────────────────────────────────────────
run-as-user  = nobody
run-as-group = nogroup

# ── Client addressing ─────────────────────────────────────────────────────────
ipv4-network = 192.168.120.0/24
dns          = 8.8.8.8
dns          = 8.8.4.4

# ── Routing ───────────────────────────────────────────────────────────────────
# Send all client traffic through the VPN:
route = default

# ── Session limits ────────────────────────────────────────────────────────────
max-clients       = 16
max-same-clients  = 2
keepalive         = 32400
dpd               = 90
mobile-dpd        = 1800

# ── TUN device ────────────────────────────────────────────────────────────────
device = vpns

# ── Compatibility ─────────────────────────────────────────────────────────────
cisco-client-compat = true
dtls-legacy         = true
